Repository jupyterlab/jupyter-collaboration, pull requests merged in 2022-11, with the labels that each got.

#46 Adds a new setting for saving document delay
  jupyter_server_ydoc/ydoc.py
Labels: enhancement

#51 Require jupyter_server_fileid
  jupyter_server_ydoc/ydoc.py
  pyproject.toml
Labels: bug

#54 Move configuration from JupyterLab
  jupyter_server_ydoc/__init__.py
  jupyter_server_ydoc/app.py
  jupyter_server_ydoc/handlers.py
  pyproject.toml
Labels: enhancement

#58 Pass logger to YRoom, require ypy-websocket >=0.5.0
  jupyter_server_ydoc/handlers.py
  pyproject.toml
Labels: enhancement

#59 Update ypy-websocket
  pyproject.toml
Labels: maintenance

#61 Add base_url to routes
  jupyter_server_ydoc/app.py
  pyproject.toml
Labels: bug

#62 Revert #61
  jupyter_server_ydoc/app.py
  pyproject.toml
Labels: bug

#63 Pass logger to YStore
  jupyter_server_ydoc/handlers.py
  pyproject.toml
Labels: enhancement

#64 Remove metadata
  jupyter_server_ydoc/app.py
  jupyter_server_ydoc/handlers.py
  pyproject.toml
Labels: enhancement
