Repository jupyterlab/jupyter-collaboration, pull requests merged in 2023-02, with the labels that each got.

#79 Update links
  CONTRIBUTING.rst
  README.md
  RELEASE.md
  package.json
  packages/collaboration/package.json
  packages/docprovider/package.json
  packages/docprovider/src/yprovider.ts
  packages/rtc-extension/package.json
Labels: documentation

#80 Adds documentation
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yaml
  CHANGELOG.md
  CONTRIBUTING.rst
  RELEASE.md
  docs/Makefile
  docs/README.md
  docs/doc-requirements.txt
  docs/environment.yml
  docs/make.bat
  docs/source/_static/jupyter_logo.svg
  docs/source/_static/jupyter_server_logo.svg
  docs/source/_static/logo-icon.png
  docs/source/conf.py
  docs/source/contributors/contributing.rst
  docs/source/index.md
  docs/source/index.rst
  docs/source/javascript_api.rst
  docs/source/overview.md
  docs/source/python_api.rst
  jupyterlab_rtc/app.py
  jupyterlab_rtc/handlers.py
  package.json
  packages/collaboration/package.json
  packages/collaboration/src/collaboratorspanel.tsx
  packages/collaboration/src/index.ts
  packages/collaboration/src/tokens.ts
  packages/collaboration/src/utils.ts
  packages/docprovider/package.json
  packages/rtc-extension/package.json
  packages/rtc-extension/src/index.ts
  pyproject.toml
  readthedocs.yml
  scripts/bump_version.py
  typedoc.json
  yarn.lock
Labels: documentation

#82 Fix releaser job
  .github/workflows/check-release.yml
  .npmignore
  package.json
  packages/collaboration/package.json
  packages/docprovider/package.json
  packages/rtc-extension/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#85 Improve the documentation
  .prettierignore
  docs/source/configuration.md
  docs/source/developer/contributing.rst
  docs/source/developer/javascript_api.rst
Labels: documentation

#87 Drop pytest_tornasync
  pyproject.toml
Labels: maintenance

#86 Improve readme
  README.md
Labels: documentation

#90 Link to the `jupyter_ydoc` repo in README.md
  README.md
Labels: documentation

#91 Rename to `jupyter_collaboration` and `@jupyter/collaboration`
  .eslintignore
  .github/workflows/test.yml
  .gitignore
  .prettierignore
  README.md
  docs/source/conf.py
  docs/source/developer/architecture.md
  docs/source/developer/contributing.rst
  docs/source/developer/python_api.rst
  docs/source/index.md
  install.json
  jupyter-config/jupyter_collaboration.json
  jupyter_collaboration/__init__.py
  jupyter_collaboration/app.py
  jupyter_collaboration/handlers.py
  lerna.json
  package.json
  packages/collaboration-extension/README.md
  packages/collaboration-extension/package.json
  packages/collaboration-extension/src/collaboration.ts
  packages/collaboration-extension/src/filebrowser.ts
  packages/collaboration/README.md
  packages/collaboration/package.json
  packages/collaboration/src/tokens.ts
  packages/docprovider/package.json
  packages/docprovider/src/yprovider.ts
  packages/docprovider/test/yprovider.spec.ts
  pyproject.toml
  typedoc.json
Labels: maintenance

#93 Add missing argument for format string (#92)
  jupyter_collaboration/handlers.py
Labels: bug

#95 Add releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#96 Publish 1.0.0alpha0
  CHANGELOG.md
  package.json
  pyproject.toml
Labels: maintenance

#97 Remove `PageConfig`
  packages/collaboration-extension/src/collaboration.ts
  packages/collaboration/src/awarenessmock.ts
  packages/collaboration/src/index.ts
Labels: bug

#98 Bump dependencies
  package.json
  packages/collaboration-extension/package.json
  packages/collaboration/package.json
  packages/docprovider/package.json
  yarn.lock
Labels: maintenance

#99 Add binder
  .github/workflows/binder-badge.yml
  .pre-commit-config.yaml
  README.md
  binder/environment.yml
  binder/jupyter_config.py
  binder/postBuild
  pyproject.toml
Labels: documentation

#103 Include style from dependencies
  packages/collaboration-extension/style/base.css
  packages/collaboration-extension/style/index.css
  packages/collaboration-extension/style/index.js
  packages/collaboration/style/base.css
Labels: bug
