Repository jupyterlab/jupyter-collaboration, pull requests merged in 2023-07, with the labels that each got.

#176 Fix package name of integration tests
  ui-tests/package.json
  ui-tests/yarn.lock
Labels: maintenance

#173 Improves chat
  jupyter_collaboration/handlers.py
  packages/collaboration-extension/package.json
  packages/collaboration-extension/src/collaboration.ts
  packages/collaboration/src/tokens.ts
  packages/docprovider/package.json
  packages/docprovider/src/awareness.ts
  packages/docprovider/src/tokens.ts
  pyproject.toml
  yarn.lock
Labels: enhancement

#174 Use fileId instead of path in the store
  jupyter_collaboration/handlers.py
Labels: bug

#178 Backport #177: Adds a flag to disable RTC
  jupyter_collaboration/app.py
  packages/docprovider/src/ydrive.ts
  pyproject.toml
Labels: enhancement

#175 Improves error handling when the file does not exist
  jupyter_collaboration/handlers.py
  jupyter_collaboration/rooms.py
  packages/docprovider/src/ydrive.ts
Labels: bug

#181 Adds tests for rooms
  tests/test_loaders.py
  tests/test_rooms.py
  tests/utils.py
Labels: maintenance
