Repository jupyterlab/jupyter-collaboration, pull requests merged in 2023-05, with the labels that each got.

#143 Fix asyncio.Task type for python<=3.8
  jupyter_collaboration/handlers.py
Labels: bug, maintenance

#144 Add JavaScript and lab extension test in CI
  .github/workflows/test.yml
  .gitignore
  packages/collaboration/babel.config.js
  packages/docprovider/jest.config.js
  packages/docprovider/package.json
  packages/docprovider/src/__tests__/yprovider.spec.ts
  packages/docprovider/tsconfig.json
  yarn.lock
Labels: maintenance

#147 Add license to files automatically
  .github/workflows/license-header.yml
  .licenserc.yaml
Labels: maintenance

#148 Wait for the document to be synced
  docs/source/developer/contributing.rst
  jupyter_collaboration/__init__.py
  jupyter_collaboration/loaders.py
  jupyter_collaboration/rooms.py
  jupyter_collaboration/utils.py
  packages/collaboration-extension/src/filebrowser.ts
  packages/docprovider/src/requests.ts
  packages/docprovider/src/yprovider.ts
  pyproject.toml
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/test_ydoc.py
Labels: bug

#146 Improve code architecture
  .gitignore
  docs/source/developer/contributing.rst
  jupyter_collaboration/app.py
  jupyter_collaboration/handlers.py
  jupyter_collaboration/loaders.py
  jupyter_collaboration/rooms.py
  jupyter_collaboration/websocketserver.py
  pyproject.toml
  tests/test_loaders.py
  tests/test_ydoc.py
Labels: enhancement

#154 Support file types
  jupyter_collaboration/handlers.py
  jupyter_collaboration/loaders.py
  jupyter_collaboration/rooms.py
  jupyter_collaboration/utils.py
  packages/docprovider/src/yprovider.ts
Labels: bug
