Repository jupyterlab/jupyter-collaboration, pull requests merged in 2023-06, with the labels that each got.

#156 Remove spurious `'`
  packages/collaboration-extension/src/filebrowser.ts
Labels: maintenance

#159 Fix package name in README
  README.md
Labels: documentation

#166 Fix install instructions to use correct name
  docs/source/index.md
Labels: documentation

#167 Chat subprotocol
  jupyter_collaboration/handlers.py
  jupyter_collaboration/utils.py
  packages/collaboration-extension/src/collaboration.ts
  packages/collaboration/package.json
  packages/collaboration/src/tokens.ts
  packages/docprovider/src/awareness.ts
  packages/docprovider/src/index.ts
  packages/docprovider/src/tokens.ts
  yarn.lock
Labels: enhancement

#169 Remove link share mention
  docs/source/index.md
Labels: documentation
