Repository jupyterlab/jupyter-collaboration, pull requests merged in 2023-03, with the labels that each got.

#108 Creates document session
  jupyter_collaboration/app.py
  jupyter_collaboration/handlers.py
  packages/collaboration-extension/src/filebrowser.ts
  packages/docprovider/src/requests.ts
  packages/docprovider/src/ydrive.ts
  packages/docprovider/src/yprovider.ts
Labels: bug

#114 Update ydoc
  packages/collaboration-extension/package.json
  packages/docprovider/package.json
  yarn.lock
Labels: bug

#113 Backport PR #108 on branch 0.8.x (Creates document session)
  .pre-commit-config.yaml
  jupyter_server_ydoc/__init__.py
  jupyter_server_ydoc/app.py
  jupyter_server_ydoc/handlers.py
Labels: bug

#115 Automated Changelog Entry for 0.8.0a0 on 0.8.x
  CHANGELOG.md
Labels: documentation

#116 Automated Changelog Entry for 0.8.0 on 0.8.x
  CHANGELOG.md
Labels: documentation

#117 Fixes experimental document-wide undo/redo flag
  package.json
  packages/collaboration-extension/package.json
  packages/collaboration-extension/src/filebrowser.ts
  packages/docprovider/src/ydrive.ts
  packages/docprovider/src/yprovider.ts
Labels: bug

#118 Remove a console.debug for plugin activate
  packages/collaboration-extension/src/filebrowser.ts
Labels: maintenance

#119 Fix pre-commit EOF error
  .pre-commit-config.yaml
Labels: maintenance

#120 Save if the document has no provider
  packages/docprovider/src/ydrive.ts
Labels: enhancement

#123 Bump dependencies
  .gitignore
  .yarnrc.yml
  package.json
  packages/collaboration-extension/package.json
  packages/collaboration/package.json
  packages/docprovider/package.json
  yarn.lock
Labels: maintenance

#125 Fix yarn on releaser
  pyproject.toml
Labels: bug

#122 Display remote user cursors
  packages/collaboration-extension/package.json
  packages/collaboration-extension/src/collaboration.ts
  packages/collaboration-extension/src/index.ts
  packages/collaboration/package.json
  packages/collaboration/src/cursors.ts
  packages/collaboration/src/index.ts
  yarn.lock
Labels: enhancement

#127 Removes drive name from file path
  packages/collaboration/src/collaboratorspanel.tsx
Labels: bug

#126 Removes deprecated endpoints
  .github/workflows/test.yml
  jupyter_collaboration/app.py
  jupyter_collaboration/handlers.py
  packages/collaboration-extension/src/collaboration.ts
Labels: enhancement

#130 Fix missing scrollbar when there are many collaborators
  packages/collaboration/src/collaboratorspanel.tsx
  packages/collaboration/style/sidepanel.css
Labels: bug

#131 Justify content in side panel
  packages/collaboration-extension/src/collaboration.ts
Labels: bug

#133 Allow other extensions to register shared models
  packages/collaboration-extension/src/filebrowser.ts
  packages/collaboration-extension/src/index.ts
  packages/docprovider/src/index.ts
  packages/docprovider/src/tokens.ts
  packages/docprovider/src/ydrive.ts
Labels: enhancement

#134 Update dependencies
  packages/collaboration-extension/package.json
  packages/collaboration/package.json
  packages/docprovider/package.json
  yarn.lock
Labels: maintenance

#136 Follow up #133
  packages/collaboration-extension/src/filebrowser.ts
  packages/docprovider/src/ydrive.ts
Labels: enhancement
