Repository jupyterlab/jupyter-collaboration, pull requests merged in 2023-04, with the labels that each got.

#121 Creates a new FileLoader class to separate the logic of watching files
  jupyter_collaboration/app.py
  jupyter_collaboration/handlers.py
  jupyter_collaboration/loaders.py
  jupyter_collaboration/rooms.py
  jupyter_collaboration/stores.py
  jupyter_collaboration/utils.py
  packages/docprovider/src/ydrive.ts
  pyproject.toml
Labels: enhancement

#138 Fix metadata
  jupyter_collaboration/loaders.py
  jupyter_collaboration/rooms.py
  pyproject.toml
Labels: bug

#139 Emit events for collaborative sessions
  jupyter_collaboration/app.py
  jupyter_collaboration/events/session.yaml
  jupyter_collaboration/handlers.py
  jupyter_collaboration/rooms.py
  jupyter_collaboration/utils.py
  package.json
  packages/collaboration-extension/package.json
  packages/collaboration-extension/src/filebrowser.ts
  packages/collaboration-extension/src/index.ts
  packages/collaboration/package.json
  packages/docprovider/package.json
  packages/docprovider/src/ydrive.ts
  pyproject.toml
  yarn.lock
Labels: enhancement

#140 Fix typo and punctuation
  packages/collaboration-extension/src/filebrowser.ts
Labels: maintenance

#141 Update lab
  binder/environment.yml
  packages/collaboration-extension/package.json
  packages/collaboration/package.json
  packages/docprovider/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance
