Repository jupyterlab/jupyter-collaboration, pull requests merged in 2024-04, with the labels that each got.

#277 Fix UI tests
  ui-tests/package.json
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/collaborationPanelCollapsed-linux.png
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/three-client-with-document-linux.png
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/three-client-without-document-linux.png
  ui-tests/tests/notebook.spec.ts
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-host-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-host-linux.png
  ui-tests/tests/user-menu.spec.ts
  ui-tests/tests/user-menu.spec.ts-snapshots/shared-link-icon-linux.png
  ui-tests/yarn.lock
Labels: maintenance

#278 Workaround shutdown issue with `aiosqlite` for now
  tests/test_documents.py
Labels: maintenance

#279 Support server-side execution
  .github/workflows/test.yml
  docs/source/configuration.md
  jupyter_collaboration/app.py
  packages/collaboration-extension/package.json
  packages/collaboration-extension/src/collaboration.ts
  packages/collaboration-extension/src/index.ts
  packages/docprovider/jest.config.js
  pyproject.toml
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-host-linux.png
  yarn.lock
Labels: enhancement

#275 Add a public API for getting a read-only view of the shared model
  docs/source/developer/python_api.rst
  jupyter_collaboration/app.py
  jupyter_collaboration/handlers.py
  jupyter_collaboration/utils.py
  tests/test_app.py
Labels: enhancement

#282 Only include `docprovider` packages in its sdist
  projects/jupyter-docprovider/pyproject.toml
Labels: maintenance

#285 Rename the docprovider destination name to avoid conficts
  projects/jupyter-docprovider/jupyter_docprovider/__init__.py
Labels: bug

#293 Update pycrdt-websocket v0.13.0
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/rooms.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/websocketserver.py
  projects/jupyter-server-ydoc/pyproject.toml
Labels: maintenance

#289 handle exception when websocket server start room failed
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/loaders.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/rooms.py
  tests/test_handlers.py
Labels: enhancement
