Repository jupyterlab/jupyter-collaboration, pull requests merged in 2024-12, with the labels that each got.

#412 Update with jupyter-ydoc v3.0.2
  projects/jupyter-server-ydoc/pyproject.toml
  ui-tests/playwright.config.js
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/collaborationPanelCollapsed-linux.png
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/three-client-with-document-linux.png
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/three-client-without-document-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-host-linux.png
Labels: maintenance

#413 Fix rename
  packages/docprovider/src/ydrive.ts
Labels: bug

#379 Users item toolbar
  packages/collaboration-extension/package.json
  packages/collaboration/src/index.ts
  packages/collaboration/src/users-item.tsx
  packages/collaboration/style/base.css
  packages/collaboration/style/users-item.css
  packages/collaborative-drive/package.json
  packages/docprovider-extension/package.json
  packages/docprovider/package.json
  yarn.lock
Labels: enhancement

#420 Gracefully handling non-existing fork room
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
Labels: enhancement

#421 Update event schema version type
  projects/jupyter-server-ydoc/jupyter_server_ydoc/events/awareness.yaml
  projects/jupyter-server-ydoc/jupyter_server_ydoc/events/fork.yaml
  projects/jupyter-server-ydoc/jupyter_server_ydoc/events/session.yaml
  pyproject.toml
  ui-tests/playwright.config.js
Labels: maintenance
