Repository jupyterlab/jupyter-collaboration, pull requests merged in 2024-03, with the labels that each got.

#241 Fix cancellation of file save operation
  jupyter_collaboration/rooms.py
Labels: bug

#258 Bump jupyter_events to 0.10.0
  pyproject.toml
Labels: maintenance

#251 Add test for document dirty attribute
  pyproject.toml
  tests/conftest.py
  tests/test_documents.py
Labels: maintenance

#255 Fix concurrent room initialization
  jupyter_collaboration/handlers.py
  jupyter_collaboration/rooms.py
  tests/test_documents.py
Labels: bug, maintenance

#259 Make user's cursor "tooltip-on-hover" faster and wider
  packages/collaboration/src/cursors.ts
Labels: enhancement

#264 Fix slow room opening
  jupyter_collaboration/handlers.py
  tests/test_documents.py
Labels: bug

#267 Update Release Scripts
  .github/workflows/prep-release.yml
  .github/workflows/publish-changelog.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#266 Use WebSocket _room_id attribute directly
  jupyter_collaboration/handlers.py
Labels: bug

#268 Fix releaser
  .github/workflows/publish-release.yml
Labels: bug
