Repository jupyterlab/jupyter-collaboration, pull requests merged in 2024-11, with the labels that each got.

#394 Add forking API
  .github/workflows/test.yml
  projects/jupyter-server-ydoc/jupyter_server_ydoc/app.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/events/fork.yaml
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/pytest_plugin.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/utils.py
  projects/jupyter-server-ydoc/pyproject.toml
  tests/test_handlers.py
Labels: enhancement

#396 Update CI
  .github/workflows/test.yml
  .github/workflows/update_galata_references.yaml
  docs/source/developer/contributing.rst
  package.json
  scripts/dev_install.py
  tsconfig.json
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/one-client-with-two-documents-linux.png
  ui-tests/tests/notebook.spec.ts
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-host-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#401 Fix open path error with timeline feature
  packages/docprovider-extension/src/filebrowser.ts
  ui-tests/tests/timeline-slider.spec.ts
Labels: bug

#402 Fix timeline feature error when base url is set
  .github/workflows/test.yml
  packages/docprovider-extension/src/filebrowser.ts
  packages/docprovider/src/TimelineSlider.tsx
  packages/docprovider/src/component.tsx
  ui-tests/package.json
  ui-tests/playwright.timeline.config.js
  ui-tests/tests/timeline-slider.spec.ts
Labels: bug
