Repository jupyterlab/jupyter-collaboration, pull requests merged in 2024-07, with the labels that each got.

#322 Fix use of traitlets to configure YStore class
  projects/jupyter-server-ydoc/jupyter_server_ydoc/app.py
  tests/conftest.py
  tests/test_app.py
Labels: bug

#331 Remove @jupyter/collaboration dependency from @jupyter/docprovider
  packages/collaboration-extension/src/collaboration.ts
  packages/collaboration/package.json
  packages/collaboration/src/tokens.ts
  packages/docprovider-extension/package.json
  packages/docprovider-extension/src/filebrowser.ts
  packages/docprovider/src/tokens.ts
  yarn.lock
Labels: maintenance

#327 Move fixtures to `jupyter_server_ydoc.pytest_plugin`
  projects/jupyter-server-ydoc/jupyter_server_ydoc/pytest_plugin.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/test_utils.py
  tests/conftest.py
  tests/test_app.py
  tests/test_loaders.py
Labels: enhancement

#329 Add notebook test for `get_document`, fix fixture when `store=True`
  projects/jupyter-server-ydoc/jupyter_server_ydoc/pytest_plugin.py
  tests/test_app.py
Labels: maintenance

#323 Bump pycrdt-websocket>=0.14.0,<0.15.0
  jupyter_collaboration/handlers.py
  pyproject.toml
Labels: maintenance
