Repository jupyterlab/jupyter-collaboration, pull requests merged in 2024-05, with the labels that each got.

#296 Backport 'Update pycrdt-websocket v0.13.0' #293
  jupyter_collaboration/handlers.py
  jupyter_collaboration/rooms.py
  jupyter_collaboration/websocketserver.py
  pyproject.toml
Labels: maintenance

#298 Backport 'handle exception when websocket server start room failed' #289
  jupyter_collaboration/handlers.py
  jupyter_collaboration/loaders.py
  jupyter_collaboration/rooms.py
  jupyter_collaboration/utils.py
  tests/test_handlers.py
Labels: bug

#297 Backport 'Log (instead of raise) exceptions when running as a server extension' #295
  jupyter_collaboration/app.py
  jupyter_collaboration/handlers.py
  jupyter_collaboration/rooms.py
  jupyter_collaboration/websocketserver.py
  pyproject.toml
Labels: bug

#299 adding await ystore start method in prepare method
  jupyter_collaboration/rooms.py
  pyproject.toml
Labels: bug

#304 Fix writing settings in page_config
  projects/jupyter-server-ydoc/jupyter_server_ydoc/app.py
Labels: bug

#305 Update JupyterLab 4.2.0 and fix test start store
  packages/collaboration-extension/package.json
  packages/docprovider-extension/package.json
  packages/docprovider/package.json
  tests/conftest.py
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-host-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-host-linux.png
  yarn.lock
Labels: maintenance

#303 Start ystore in a task
  projects/jupyter-server-ydoc/jupyter_server_ydoc/rooms.py
  projects/jupyter-server-ydoc/pyproject.toml
Labels: enhancement

#287 Add the list of opened shared documents to the user awareness
  packages/collaboration-extension/src/collaboration.ts
  packages/collaboration/package.json
  packages/collaboration/src/collaboratorspanel.tsx
  packages/collaboration/src/tokens.ts
  packages/collaboration/style/sidepanel.css
  packages/docprovider-extension/package.json
  packages/docprovider-extension/src/filebrowser.ts
  packages/docprovider/src/ydrive.ts
  ui-tests/tests/collaborationpanel.spec.ts
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/one-client-with-two-documents-linux.png
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/three-client-with-document-linux.png
  ui-tests/tests/collaborationpanel.spec.ts-snapshots/three-client-without-document-linux.png
  yarn.lock
Labels: enhancement
