Repository jupyterlab/jupyter-collaboration, pull requests merged in 2024-10, with the labels that each got.

#368 Fix model format
  packages/docprovider/src/ydrive.ts
Labels: bug

#369 Backport 'Fix model format' #368
  packages/docprovider/src/ydrive.ts
Labels: maintenance

#367 Update jupyter_ydoc and pycrdt_websocket dependencies
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/rooms.py
  projects/jupyter-server-ydoc/pyproject.toml
Labels: enhancement

#376 Backport 'Update jupyter_ydoc and pycrdt_websocket dependencies' #367
  jupyter_collaboration/handlers.py
  jupyter_collaboration/rooms.py
  pyproject.toml
Labels: maintenance

#343 Fix bump file
  projects/jupyter-collaboration/pyproject.toml
  pyproject.toml
  scripts/bump_version.py
Labels: maintenance

#375 Updates warning message on double file open
  packages/docprovider-extension/src/filebrowser.ts
Labels: enhancement

#373 Fix errors in contributing.rst for setup
  docs/source/developer/contributing.rst
Labels: documentation

#316 [2.x] Support @jupyter/ydoc 2.x
  packages/collaboration-extension/package.json
  packages/collaboration/src/collaboratorspanel.tsx
  packages/collaboration/src/tokens.ts
  packages/docprovider/package.json
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-create-notebook-host-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-guest-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/initialization-open-notebook-host-linux.png
  yarn.lock
Labels: bug

#383 Add check for user value in CollaboratorsPanel
  packages/collaboration/src/collaboratorspanel.tsx
Labels: bug

#384 Update test workflow
  .github/workflows/test.yml
Labels: maintenance

#388 Bump jupyter-ydoc v3.0.0
  packages/collaboration-extension/package.json
  packages/collaborative-drive/package.json
  packages/docprovider-extension/package.json
  packages/docprovider/package.json
  yarn.lock
Labels: maintenance

#389 Add `packages/collaborative-drive` to the typedoc config
  typedoc.json
Labels: documentation
