Repository jupyterlab/jupyter-collaboration, pull requests merged in 2024-09, with the labels that each got.

#338 Implementing Collaborative Timeline Slider with Undo/Redo Functionality
  packages/docprovider-extension/src/filebrowser.ts
  packages/docprovider-extension/src/index.ts
  packages/docprovider/src/TimelineSlider.tsx
  packages/docprovider/src/component.tsx
  packages/docprovider/src/index.ts
  packages/docprovider/src/requests.ts
  packages/docprovider/src/ydrive.ts
  packages/docprovider/src/yprovider.ts
  packages/docprovider/style/base.css
  packages/docprovider/style/index.css
  packages/docprovider/style/index.js
  packages/docprovider/style/slider.css
  projects/jupyter-server-ydoc/jupyter_server_ydoc/app.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
  projects/jupyter-server-ydoc/pyproject.toml
  yarn.lock
Labels: enhancement

#346 Remove unused chat feature
  packages/docprovider/src/awareness.ts
  packages/docprovider/src/tokens.ts
  packages/docprovider/src/utils.ts
Labels: maintenance

#349 Handle generic document types in timeline
  packages/docprovider-extension/src/filebrowser.ts
  packages/docprovider/src/tokens.ts
  packages/docprovider/src/ydrive.ts
Labels: enhancement

#355 Add missing aria label to the file browser
  packages/docprovider-extension/src/filebrowser.ts
Labels: enhancement

#356 Remove the unused `ISettingRegistry` token from the file browser plugin
  packages/docprovider-extension/src/filebrowser.ts
Labels: bug

#358 Fix mypy
  .pre-commit-config.yaml
  pyproject.toml
  scripts/bump_version.py
Labels: maintenance

#359 Fix ignoring AnyIO warnings in tests
  pyproject.toml
Labels: maintenance

#360 Ignore github.com in check-links
  .github/workflows/test.yml
Labels: maintenance

#361 Backport 'Fix mypy' #358
  .pre-commit-config.yaml
  pyproject.toml
  scripts/bump_version.py
Labels: maintenance

#362 Backport 'Fix ignoring AnyIO warnings in tests' #359
  pyproject.toml
Labels: maintenance

#342 Initialize and update the ydoc path property
  projects/jupyter-server-ydoc/jupyter_server_ydoc/loaders.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/rooms.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/test_utils.py
  tests/test_rooms.py
Labels: bug
