Repository jupyterlab/jupyter-collaboration, pull requests merged in 2025-04, with the labels that each got.

#458 Bump to jupyterlab v4.4.0
  packages/collaboration-extension/package.json
  packages/collaboration/package.json
  packages/collaborative-drive/package.json
  packages/docprovider-extension/package.json
  packages/docprovider/package.json
  pyproject.toml
  scripts/dev_install.py
  yarn.lock
Labels: maintenance

#457 Skip saving non-writable files
  projects/jupyter-server-ydoc/jupyter_server_ydoc/loaders.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/pytest_plugin.py
  tests/test_rooms.py
Labels: bug

#459 3.x: Fix pinnings
  projects/jupyter-collaboration/pyproject.toml
Labels: bug

#461 Fix version pins in bump script
  scripts/bump_version.py
Labels: bug

#467 Update the pre-commit action to v3.0.1
  .github/workflows/test.yml
Labels: maintenance

#463 Fix jupyterlab dependency dropped by the version bump script
  projects/jupyter-collaboration/pyproject.toml
  scripts/bump_version.py
Labels: bug

#468 Backport PR #461 on branch main (Fix version pins in bump script)
  scripts/bump_version.py
Labels: bug

#471 Fix "Edit on GitHub" link in documentation
  docs/source/conf.py
Labels: documentation

#472 Reset dirty state only when the file is saved
  projects/jupyter-server-ydoc/jupyter_server_ydoc/rooms.py
Labels: bug

#475 Fix cleanup logic and suppress repetitive error logs
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/loaders.py
Labels: bug

#478 Remove suspected unused code
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
Labels: maintenance

#476 Force analysis of `pycrdt_websocket` imports, fix types
  .pre-commit-config.yaml
  projects/jupyter-server-ydoc/jupyter_server_ydoc/app.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/handlers.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/pytest_plugin.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/rooms.py
  projects/jupyter-server-ydoc/jupyter_server_ydoc/websocketserver.py
Labels: bug
